# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Login to Azure Container Registry
      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: judevops.azurecr.io
          username: ${{ secrets.DEVOPS_USERNAME }}
          password: ${{ secrets.DEVOPS_PASSWORD }}
          
      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r ./BE/requirements.txt

      # Start Calculator REST API (localhost service)
      - name: Start Calculator REST API
        run: |
          python ./BE/calculator.py --rest &
          
      - name: Wait for service to start
        run: |
          sleep 5
          
      - name: Set python path
        run: |
          echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      # Run tests
      - name: Build and run tests
        run: |
          pytest --junit-xml=report.xml
      - name: Publish test report
        uses: actions/upload-artifact@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: './tests/report.xml'

      # Create Docker image      
      - name: Build Docker image
        run: |
          docker build -t judevops.azurecr.io/albin_fridh-calculator ./BE
          
      # Push Docker image    
      - name: Push Docker image
        run: |
          docker push judevops.azurecr.io/albin_fridh-calculator
          
